# FROM python:3.10
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# # COPY app/ /app
# COPY ../ /.
# EXPOSE 8501
# ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]


FROM python:3.10

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

# COPY . /app/

COPY app/ /app/app/
COPY etl/ /app/etl/
COPY models/ /app/models/

ENV PYTHONPATH="/app"

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
